language: java
sudo: false
jdk: oraclejdk8
before_install:
- chmod +x gradlew
script:
- "./gradlew check"
deploy:
  provider: releases
  api_key:
    secure: RKWh9K+2+hdJx3OtiAEF9rE8Ln7qUreX7bHxecuIriA04QZgvpWHjHbS7Jn466UB7GqvLzc5sZuB44w/93a0epzYGVP+I5UXkXHJGxPjObd5zJmXLZuaLqI3mitls5aN+muB5yn3f1HZRFGRTU/40ZEnI7/aPns1XSrvvXjJ+yYuu9c2CWwSBviSE9buzCAkdA9O7WhnN17VJ7hgUlRzITYBrM8oCmzoJl50HqZ9+EB0oq9H/2+nDEHq6TS0XtKfj/leCpgD6RNKME9+F/qY6eLVQcukyygT73RyRKejCex4d5x6eNdSkAxOkeNl/zL1vD2h45zN1FZusmggVYi+Oqrk77ndksZmm6rtZCTNWu92s4j15I16XdZ8DdZdfLCz3aV4PK13DqD4X/Vykj45Ef7UEqJ7+ywvrcfuPBH23zR6eEvr+9j3Yzj9zonKfAHKoJiQBvOB+OUVYXFn+wDblUMKX4ECSbeyQGJEHUniVmvGl0tTtUcqNBaPpXA8r2eHm3564/RvRoQ412cJG6xMgCuYsC6jj3eQKgUNM6G7kEOcG+LygwssfnX8DaugtgBWrNaP2HduTWu7ePBFmTd1TPI2tm2c6F4RNSR6SvBowHlPN9bExQi08evoaGkw4MDfnm8wmfe0OzhXe4wWZX1EBs/OYfhO9VimM6sMIjMP5EE=
  file: "${HOME}/build/libs/*.jar"
  file_glob: "true"
  skip_cleanup: true
  on:
    repo: Growlith1223/ArsMagica2
    branch: 1.10.2
    tags: true
